<?php
namespace App\Repository;


use App\Entity\Foo;
use Laventure\Component\Database\ORM\Manager\EntityManager;
use Laventure\Component\Database\ORM\Repository\ServiceRepository;


/**
 * @FooRepository
 *
 * @package App\Repository
 *
 * <Generated By Laventure 05/04/2022 16:38:14>
*/
class FooRepository extends ServiceRepository
{

       /**
        * FooRepository constructor.
        *
        * @param EntityManager $em
       */
       public function __construct(EntityManager $em)
       {
            parent::__construct($em, Foo::class);
       }


       /**
        * @return
       */
       public function getExampleSomething()
       {

       }
}
