<?php
namespace App\Repository;


use App\Entity\Region;
use Laventure\Component\Database\ORM\Manager\EntityManager;
use Laventure\Component\Database\ORM\Repository\ServiceRepository;


/**
 * @RegionRepository
 *
 * @package App\Repository
 *
 * <Generated By Laventure 05/04/2022 06:45:16>
*/
class RegionRepository extends ServiceRepository
{

       /**
        * RegionRepository constructor.
        *
        * @param EntityManager $em
       */
       public function __construct(EntityManager $em)
       {
            parent::__construct($em, Region::class);
       }


       /**
        * @return
       */
       public function getExampleSomething()
       {

       }
}
