<?php
namespace App\Http\Controller\Api;


use Laventure\Component\Http\Request\Request;
use Laventure\Component\Http\Response\Response;
use Laventure\Foundation\Routing\Controller;


/**
 * @ProductController
 *
 * @package App\Http\Controller\Api
 *
 * <Generated By Laventure 03/04/2022 18:26:47>
*/
class ProductController extends Controller
{

         
        /**
         * @param Request $request
         * @return Response
        */
        public function index(Request $request): Response
        {
               return $this->render('api/product/index.php');
        }
}
