<?php
namespace App\Http\Controller\Api;


use Laventure\Foundation\Routing\Controller;


/**
 * Class UserController
 * @package App\Http\Controller\Api
 *
 * <Generated By Laventure 03/04/2022 03:46:57>
*/
class UserController extends Controller
{

         
}
