<?php
namespace App\Http\Controller;


use Laventure\Component\Http\Request\Request;
use Laventure\Component\Http\Response\Response;
use Laventure\Foundation\Routing\Controller;


/**
 * @BlogController
 *
 * @package App\Http\Controller
 *
 * <Generated By Laventure 06/04/2022 05:11:54>
*/
class BlogController extends Controller
{

         
        /**
         * @Route(methods="GET", path="blog", name="blog.index")
         *
         * @param Request $request
         * @return Response
        */
        public function index(Request $request): Response
        {
               return $this->render('blog/list.php');
        }
}
