<?php
namespace App\Http\Controller;


use Laventure\Component\Http\Request\Request;
use Laventure\Component\Http\Response\Response;
use Laventure\Foundation\Routing\Controller;


/**
 * @FooController
 *
 * @package App\Http\Controller
 *
 * <Generated By Laventure 06/04/2022 19:28:53>
*/
class FooController extends Controller
{

         
        /**
         * @Route(methods="GET", path="foo", name="foo.index")
         *
         * @param Request $request
         * @return Response
        */
        public function index(Request $request): Response
        {
               return $this->render('foo/index.php');
        }
}
