<?php
namespace App\Http\Controller;


use Laventure\Component\Http\Request\Request;
use Laventure\Component\Http\Response\Response;
use Laventure\Foundation\Routing\Controller;


/**
 * @HelloController
 *
 * @package App\Http\Controller
 *
 * <Generated By Laventure 05/04/2022 04:52:45>
*/
class HelloController extends Controller
{

         
        /**
         * @param Request $request
         * @return Response
        */
        public function index(Request $request): Response
        {
               return $this->render('hello/index.php');
        }
}
