<?php
namespace App\Http\Controller;


use Laventure\Component\Http\Request\Request;
use Laventure\Component\Http\Response\Response;
use Laventure\Foundation\Routing\Controller;


/**
 * @PostController
 *
 * @package App\Http\Controller
 *
 * <Generated By Laventure 07/04/2022 17:42:05>
*/
class PostController extends Controller
{

         
        /**
         * @Route(methods="GET", path="post", name="post.index")
         *
         * @param Request $request
         * @return Response
        */
        public function index(Request $request): Response
        {
               return $this->render('post/index.php');
        }
}
