<?php
namespace App\Http\Controller\Magazin\Module;


use Laventure\Component\Http\Request\Request;
use Laventure\Component\Http\Response\Response;
use Laventure\Foundation\Routing\Controller;


/**
 * @ShopController
 *
 * @package App\Http\Controller\Magazin\Module
 *
 * <Generated By Laventure 08/04/2022 00:02:44>
*/
class ShopController extends Controller
{

         
        /**
         * @Route(methods="GET", path="magazin/module/shop", name="magazin.module.shop.index")
         *
         * @param Request $request
         * @return Response
        */
        public function index(Request $request): Response
        {
               return $this->render('magazin/module/shop/index.php');
        }
}
