<?php
namespace App\Repository\Module;


use App\Entity\Module\Personal;
use Laventure\Component\Database\ORM\Manager\EntityManager;
use Laventure\Component\Database\ORM\Repository\ServiceRepository;


/**
 * @PersonalRepository
 *
 * @package App\Repository\Module
 *
 * <Generated By Laventure 05/04/2022 06:46:03>
*/
class PersonalRepository extends ServiceRepository
{

       /**
        * PersonalRepository constructor.
        *
        * @param EntityManager $em
       */
       public function __construct(EntityManager $em)
       {
            parent::__construct($em, Personal::class);
       }


       /**
        * @return
       */
       public function getExampleSomething()
       {

       }
}
