<?php
namespace App\Migration;


use Laventure\Component\Database\Migration\Migration;


/**
 * Class Version20220401002641
 *
 * @package App\Migration
 *
 * <Generated By Laventure 01/04/2022 00:26:41>
*/
class Version20220401002641 extends Migration
{


    /**
      * @return void
    */
    public function up()
    {
        /*
        Schema::create('tableName', function (BluePrint $table) {
            $table->increments('id');
            // ...
        });
        */
    }


    /**
     * @return void
    */
    public function down()
    {
        /*
        Schema::dropIfExists('tableName');
        */
    }
}
