<?php
namespace App\Fixtures;


use Laventure\Component\Database\ORM\Manager\Contract\ObjectManager;
use Laventure\Component\Database\ORM\Manager\Fixtures\Contract\Fixture;


/**
 * @ProductFixture
 *
 * @package App\Fixtures
 *
 * <Generated By Laventure 03/04/2022 20:33:23>
*/
class ProductFixture implements Fixture
{

      /**
       * @inheritDoc
      */
      public function load(ObjectManager $manager)
      {
           // add your logic here
      }
}
