<?php
namespace App\Http\Controller\Admin;


use Laventure\Component\Http\Request\Request;
use Laventure\Component\Http\Response\Response;
use Laventure\Foundation\Routing\Controller;


/**
 * Class DashboardController
 * @package App\Http\Controller\Admin
 *
 * <Generated By Laventure 03/04/2022 05:58:03>
*/
class DashboardController extends Controller
{

         
}
