<?php
namespace App\Http\Controller\Admin;


use Laventure\Component\Http\Request\Request;
use Laventure\Component\Http\Response\Response;
use Laventure\Foundation\Routing\Controller;


/**
 * @PostController
 *
 * @package App\Http\Controller\Admin
 *
 * <Generated By Laventure 07/04/2022 18:18:25>
*/
class PostController extends Controller
{

         
        /**
         * @Route(methods="GET", path="admin/post", name="admin.post.index")
         *
         * @param Request $request
         * @return Response
        */
        public function index(Request $request): Response
        {
               return $this->render('admin/post/index.php');
        }
}
