<?php
namespace App\Http\Controller\Admin;


use Laventure\Foundation\Routing\Controller;


/**
 * Class UserController
 * @package App\Http\Controller\Admin
 *
 * <Generated By Laventure 03/04/2022 03:46:50>
*/
class UserController extends Controller
{

         
}
